openapi: 3.1.0
info:
  version: 1.0.0
  title: Reviews/Courses Microservice API
  description: API for the reviews/courses microservice of the FIS-G4 project.
  contact:
    name: Mathew Byte
    email: ""
    url: https://github.com/fis-g4/courses-microservice
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8000/v1/reviews
  - url: http://localhost:8000/v1/courses
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths: {}
tags: []
